### ISSUE TITLE
有时候无通知,也会亮屏

### ISSUE THREAD

**Issue by leychan** [SymeonChen/WakeUpScreen#12]
你好: 有时候手机亮屏,然后发现没有收到通知,不知道是怎么回事,

**Comment by SymeonChen** [comment]
这个问题是因为有应用推送了未显示在通知栏的通知消息，你可以通过如下步骤开启通知日志：

1. 打开app->设置->调试模式->开启 
2. 进入锁屏状态，接收若干条通知
3. 打开app->设置->调试页面，查看显示的数据

当发生无通知亮屏的情况时，进入调试页面即可看到唤醒原因。根据目前收集到的场景来分析，通常是由部分系统应用引起的。

在下个版本中我计划增加黑/白名单模式，届时可以通过设置名单的功能来避免发生该问题。

**Comment by leychan** [comment]
> 这个问题是因为有应用推送了未显示在通知栏的通知消息，你可以通过如下步骤开启通知日志：
> 
> 1. 打开app->设置->调试模式->开启
> 2. 进入锁屏状态，接收若干条通知
> 3. 打开app->设置->调试页面，查看显示的数据
> 
> 当发生无通知亮屏的情况时，进入调试页面即可看到唤醒原因。根据目前收集到的场景来分析，通常是由部分系统应用引起的。
> 
> 在下个版本中我计划增加黑/白名单模式，届时可以通过设置名单的功能来避免发生该问题。

了解,谢谢回复.
