### ISSUE TITLE
参考下这个XDA大神的作品呢

### ISSUE THREAD

**Issue by colalan** [SymeonChen/WakeUpScreen#13]
参考下这个XDA大神的作品呢
[aodNotify](https://forum.xda-developers.com/s10-plus/themes/app-aodnotify-automatically-activate-t3934237)

**Comment by SymeonChen** [comment]
谢谢你的建议，虽然本项目与该作品出发点相同，但采用了不同的解决思路，本项目暂时不会支持通知常亮功能。不过与该作品类似的分应用处理功能已经正在开发中，将在下一版本加入，感谢你的关注。
