### ISSUE TITLE
是否可以和edge light结合？

### ISSUE THREAD

**Issue by manymuch** [SymeonChen/WakeUpScreen#18]
感谢分享，一直在找类似的应用.
关闭edge light时非常好用
但是开启edge light后，亮屏显示的图标为wakeupscreen的图标,且没有通知预览
不知道这个能否实现？

**Comment by SymeonChen** [comment]
将edge light设置为【当屏幕开启时】即可互相兼容。
目前版本（v0.6-alpha）暂不支持在屏幕关闭状态下直接通过edge light来进行消息提醒，之后的版本会考虑增加该功能，感谢你的建议。
