### ISSUE TITLE
note20u 无法正常工作

### ISSUE THREAD

**Issue by Wszl** [SymeonChen/WakeUpScreen#54]
在按照指导设置完成后，仅能正常工作一小会儿，之后就不再亮屏了
系统
Android 11

**Comment by SymeonChen** [comment]
估计是后台服务被终止了，可以通过如下几个步骤让应用能够在后台持续运行：
1. 打开最近任务窗口，长按通知亮屏的图标，选择「保持打开以快速启动」。
2. 打开设置，搜索「优化电池使用量」，选择「全部」，并找到「通知亮屏」，确保其按钮是在未打开状态。

如果未生效，可以卸载重新安装后按上述步骤执行一遍。

**Comment by Wszl** [comment]
依旧无法使用。。受不了无亮屏功能。挂咸鱼了。
