### ISSUE TITLE
non-free dependency

### ISSUE THREAD

**Issue by IzzySoft** [SymeonChen/WakeUpScreen#60]
I just wonder why the [Google Play Core](https://developer.android.com/guide/playcore) library was added (especially as the app does not even access the network – at least it has no network permissions, though [VirusTotal](https://www.virustotal.com/gui/file/c1a5e835ec2c50d739182847702546e65667a385b8e24bee996ac9e0e8dbac7f/detection/f-c1a5e835ec2c50d739182847702546e65667a385b8e24bee996ac9e0e8dbac7f-1620765655) has 2 engines claiming something like "DataCollector"). That library is non-free and doesn't suit well in a FOSS app. It wasn't there when I checked last, so maybe it was just "accidentally dragged in" as dependency of something else?

**Comment by SymeonChen** [comment]
The current version integrates Google play’s advertising library, but neither old users nor new users will see it. This is my test on another project. I will remove all Google’s ad library in the next version.

In addition, this APP does not have Internet access, so it will not upload any sensitive information.

**Comment by IzzySoft** [comment]
It just triggers alerts from scanners, yes. But good to know that's only temporary – thanks!

**Comment by SymeonChen** [comment]
Version 2.2.0 has removed the play core dependencies.

Thanks for your feedback.

**Comment by IzzySoft** [comment]
Wow – and APK size down to 50%, nice side-effect :smile: Thanks a lot! AntiFeatures are removed (taking effect with the next sync in about 3h from now).

**Comment by ivysrono** [comment]
I find this app from: https://apt.izzysoft.de/fdroid/index/apk/com.symeonchen.wakeupscreen

Could you push to F-Droid?

**Comment by IzzySoft** [comment]
Nobody can "push to F-Droid" – F-Droid always pulls :smile: But one can apply for "being pulled", i.e. [Request For Packaging](https://gitlab.com/fdroid/rfp/-/issues).

**Comment by ivysrono** [comment]
https://gitlab.com/fdroid/rfp/-/issues/2023
